# Generated by Django 5.0 on 2024-03-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_borrow_book_remove_buy_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
