# Generated by Django 5.0 on 2024-03-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_product_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='image',
        ),
    ]
