# Generated by Django 5.0 on 2024-03-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_remove_product_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
