# Generated by Django 5.0 on 2024-03-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
    ]
